version: "3.3"

services:
  database:
    image: postgres:latest
    hostname: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      -  5434:5432
    env_file:
      - ./.env

  web:
    build: .
    command: python /MangaRead/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/MangaRead
    ports:
      - 8000:8000
    depends_on:
      - database

volumes:
  postgres_data:

