version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      PRODUCTION: ${PRODUCTION}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8000 core.wsgi --reload"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres_db
      - web
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data: