version: "3.9"

services:
  mango_postgres:
    image: postgres:14
    container_name: mango_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      -  5434:5432
    env_file:
      - .env 

  mango_read:
    build:
      dockerfile: Dockerfile
      context: .
    image: mr_djangorest:latest
    container_name: mr_djangorest
    depends_on:
      - mango_read
    volumes:
      -

volumes:
  postgres_data:
