version: "3.3"

services:
  mango_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      -  5434:5432
    env_file:
      - ./.env

  mango_web:
    build: .
    command: python /Manga/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api/core
    ports:
      - 8000:8000
    depends_on:
      - mango_db

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - database
  #     - web
  #   ports:
  #     - "80:80"
  #     - "440:440"

volumes:
  postgres_data: